name: build
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_aarch64_softmmu_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev libtasn1-dev ninja-build build-essential cmake python3-venv

      - name: Install lzfse
        run: |
          git clone https://github.com/lzfse/lzfse
          cd lzfse
          mkdir build
          cd build
          cmake ..
          make -j$(nproc)
          sudo make install

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build qemu
        run: |
          mkdir build
          cd build
          ../configure --target-list=aarch64-softmmu --disable-capstone --disable-slirp
          make -j$(nproc)

      - name: Install qemu
        run: |
          cd build
          make DESTDIR=$GITHUB_WORKSPACE/bin/ install

      - name: Publish binaries
        uses: actions/upload-artifact@v2
        with:
          name: aarch64_softmmu_linux
          path: ${{ github.workspace }}/bin/

  build_aarch64_softmmu_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install build dependencies
        run: |
          brew install ninja pixman

      - name: Install lzfse
        run: |
          git clone https://github.com/lzfse/lzfse
          cd lzfse
          mkdir build
          cd build
          cmake ..
          make -j$(nproc)
          sudo make install

      - name: Build qemu
        run: |
          mkdir build
          cd build
          LIBTOOL="glibtool" ../configure --target-list=aarch64-softmmu --disable-bsd-user --disable-guest-agent --enable-slirp --enable-capstone --enable-curses --enable-libssh --enable-virtfs --enable-zstd --extra-cflags=-DNCURSES_WIDECHAR=1 --disable-sdl --disable-gtk --enable-cocoa --enable-lzfse --disable-werror
          make -j$(sysctl -n hw.logicalcpu)

      - name: Install qemu
        run: |
          cd build
          make DESTDIR=$GITHUB_WORKSPACE/bin/ install

      - name: Publish binaries
        uses: actions/upload-artifact@v2
        with:
          name: aarch64_softmmu_macos
          path: ${{ github.workspace }}/bin/

  build_all_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev libtasn1-dev ninja-build build-essential cmake python3-venv

      - name: Install lzfse
        run: |
          git clone https://github.com/lzfse/lzfse
          cd lzfse
          mkdir build
          cd build
          cmake ..
          make -j$(nproc)
          sudo make install

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build qemu
        run: |
          mkdir build
          cd build
          ../configure
          make -j$(nproc)

      - name: Install qemu
        run: |
          cd build
          make DESTDIR=$GITHUB_WORKSPACE/bin/ install

      - name: Publish binaries
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: ${{ github.workspace }}/bin/

  build_all_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install build dependencies
        run: |
          brew install ninja pixman

      - name: Install lzfse
        run: |
          git clone https://github.com/lzfse/lzfse
          cd lzfse
          mkdir build
          cd build
          cmake ..
          make -j$(nproc)
          sudo make install

      - name: Build qemu
        run: |
          mkdir build
          cd build
          ../configure
          make -j$(sysctl -n hw.logicalcpu)

      - name: Install qemu
        run: |
          cd build
          make DESTDIR=$GITHUB_WORKSPACE/bin/ install

      - name: Publish binaries
        uses: actions/upload-artifact@v2
        with:
          name: macos
          path: ${{ github.workspace }}/bin/
